[package]
name = "uap"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "uap"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
uaparser = "0.6.4"
once_cell = "1.19"
